create table payment (
	id_Payment INT,
	payment_Method VARCHAR(11)
);
insert into payment (id_Payment, payment_Method) values (56346, 'credit card');
insert into payment (id_Payment, payment_Method) values (31389, 'check');
insert into payment (id_Payment, payment_Method) values (26619, 'credit card');
insert into payment (id_Payment, payment_Method) values (91412, 'paypal');
insert into payment (id_Payment, payment_Method) values (74270, 'cash');
insert into payment (id_Payment, payment_Method) values (53021, 'paypal');
insert into payment (id_Payment, payment_Method) values (26304, 'paypal');
insert into payment (id_Payment, payment_Method) values (99600, 'check');
insert into payment (id_Payment, payment_Method) values (19797, 'check');
insert into payment (id_Payment, payment_Method) values (30423, 'check');
insert into payment (id_Payment, payment_Method) values (64654, 'debit card');
insert into payment (id_Payment, payment_Method) values (79220, 'debit card');
insert into payment (id_Payment, payment_Method) values (38644, 'cash');
insert into payment (id_Payment, payment_Method) values (94288, 'debit card');
insert into payment (id_Payment, payment_Method) values (87408, 'credit card');
insert into payment (id_Payment, payment_Method) values (33243, 'credit card');
insert into payment (id_Payment, payment_Method) values (69478, 'check');
insert into payment (id_Payment, payment_Method) values (84287, 'debit card');
insert into payment (id_Payment, payment_Method) values (66240, 'check');
insert into payment (id_Payment, payment_Method) values (13677, 'check');
insert into payment (id_Payment, payment_Method) values (73693, 'credit card');
insert into payment (id_Payment, payment_Method) values (57549, 'debit card');
insert into payment (id_Payment, payment_Method) values (74207, 'debit card');
insert into payment (id_Payment, payment_Method) values (33980, 'paypal');
insert into payment (id_Payment, payment_Method) values (64666, 'paypal');
insert into payment (id_Payment, payment_Method) values (37876, 'credit card');
insert into payment (id_Payment, payment_Method) values (88387, 'paypal');
insert into payment (id_Payment, payment_Method) values (57914, 'credit card');
insert into payment (id_Payment, payment_Method) values (25910, 'paypal');
insert into payment (id_Payment, payment_Method) values (42493, 'check');
insert into payment (id_Payment, payment_Method) values (40740, 'debit card');
insert into payment (id_Payment, payment_Method) values (47644, 'debit card');
insert into payment (id_Payment, payment_Method) values (40592, 'debit card');
insert into payment (id_Payment, payment_Method) values (57941, 'check');
insert into payment (id_Payment, payment_Method) values (26741, 'check');
insert into payment (id_Payment, payment_Method) values (88422, 'paypal');
insert into payment (id_Payment, payment_Method) values (42085, 'check');
insert into payment (id_Payment, payment_Method) values (58233, 'credit card');
insert into payment (id_Payment, payment_Method) values (39666, 'paypal');
insert into payment (id_Payment, payment_Method) values (98026, 'credit card');
insert into payment (id_Payment, payment_Method) values (51912, 'debit card');
insert into payment (id_Payment, payment_Method) values (69836, 'paypal');
insert into payment (id_Payment, payment_Method) values (24612, 'cash');
insert into payment (id_Payment, payment_Method) values (34150, 'cash');
insert into payment (id_Payment, payment_Method) values (99176, 'credit card');
insert into payment (id_Payment, payment_Method) values (50287, 'credit card');
insert into payment (id_Payment, payment_Method) values (33717, 'cash');
insert into payment (id_Payment, payment_Method) values (77890, 'credit card');
insert into payment (id_Payment, payment_Method) values (75221, 'check');
insert into payment (id_Payment, payment_Method) values (18009, 'debit card');
insert into payment (id_Payment, payment_Method) values (63997, 'paypal');
insert into payment (id_Payment, payment_Method) values (75908, 'debit card');
insert into payment (id_Payment, payment_Method) values (74955, 'cash');
insert into payment (id_Payment, payment_Method) values (92945, 'check');
insert into payment (id_Payment, payment_Method) values (61211, 'check');
insert into payment (id_Payment, payment_Method) values (77029, 'check');
insert into payment (id_Payment, payment_Method) values (34564, 'credit card');
insert into payment (id_Payment, payment_Method) values (14215, 'credit card');
insert into payment (id_Payment, payment_Method) values (18494, 'debit card');
insert into payment (id_Payment, payment_Method) values (29818, 'cash');
insert into payment (id_Payment, payment_Method) values (93431, 'cash');
insert into payment (id_Payment, payment_Method) values (46606, 'debit card');
insert into payment (id_Payment, payment_Method) values (98637, 'credit card');
insert into payment (id_Payment, payment_Method) values (38878, 'credit card');
insert into payment (id_Payment, payment_Method) values (86237, 'paypal');
insert into payment (id_Payment, payment_Method) values (64743, 'check');
insert into payment (id_Payment, payment_Method) values (64390, 'paypal');
insert into payment (id_Payment, payment_Method) values (31088, 'check');
insert into payment (id_Payment, payment_Method) values (81379, 'credit card');
insert into payment (id_Payment, payment_Method) values (20033, 'credit card');
insert into payment (id_Payment, payment_Method) values (49989, 'paypal');
insert into payment (id_Payment, payment_Method) values (76130, 'debit card');
insert into payment (id_Payment, payment_Method) values (44298, 'check');
insert into payment (id_Payment, payment_Method) values (97154, 'cash');
insert into payment (id_Payment, payment_Method) values (39958, 'credit card');
insert into payment (id_Payment, payment_Method) values (33671, 'cash');
insert into payment (id_Payment, payment_Method) values (97065, 'paypal');
insert into payment (id_Payment, payment_Method) values (95271, 'credit card');
insert into payment (id_Payment, payment_Method) values (71013, 'cash');
insert into payment (id_Payment, payment_Method) values (33058, 'credit card');
insert into payment (id_Payment, payment_Method) values (47695, 'cash');
insert into payment (id_Payment, payment_Method) values (71159, 'paypal');
insert into payment (id_Payment, payment_Method) values (98458, 'paypal');
insert into payment (id_Payment, payment_Method) values (76206, 'check');
insert into payment (id_Payment, payment_Method) values (74092, 'credit card');
insert into payment (id_Payment, payment_Method) values (72876, 'debit card');
insert into payment (id_Payment, payment_Method) values (85714, 'credit card');
insert into payment (id_Payment, payment_Method) values (72904, 'paypal');
insert into payment (id_Payment, payment_Method) values (13287, 'paypal');
insert into payment (id_Payment, payment_Method) values (27103, 'paypal');
insert into payment (id_Payment, payment_Method) values (78672, 'credit card');
insert into payment (id_Payment, payment_Method) values (99851, 'cash');
insert into payment (id_Payment, payment_Method) values (13063, 'credit card');
insert into payment (id_Payment, payment_Method) values (17383, 'debit card');
insert into payment (id_Payment, payment_Method) values (39480, 'cash');
insert into payment (id_Payment, payment_Method) values (99004, 'check');
insert into payment (id_Payment, payment_Method) values (36712, 'paypal');
insert into payment (id_Payment, payment_Method) values (98150, 'check');
insert into payment (id_Payment, payment_Method) values (31933, 'debit card');
insert into payment (id_Payment, payment_Method) values (95881, 'paypal');
insert into payment (id_Payment, payment_Method) values (73426, 'credit card');
insert into payment (id_Payment, payment_Method) values (82498, 'cash');
insert into payment (id_Payment, payment_Method) values (16212, 'check');
insert into payment (id_Payment, payment_Method) values (81497, 'check');
insert into payment (id_Payment, payment_Method) values (21012, 'paypal');
insert into payment (id_Payment, payment_Method) values (80846, 'debit card');
insert into payment (id_Payment, payment_Method) values (56225, 'check');
insert into payment (id_Payment, payment_Method) values (76759, 'check');
insert into payment (id_Payment, payment_Method) values (94026, 'credit card');
insert into payment (id_Payment, payment_Method) values (25688, 'credit card');
insert into payment (id_Payment, payment_Method) values (76001, 'paypal');
insert into payment (id_Payment, payment_Method) values (93462, 'credit card');
insert into payment (id_Payment, payment_Method) values (56808, 'credit card');
insert into payment (id_Payment, payment_Method) values (46927, 'credit card');
insert into payment (id_Payment, payment_Method) values (69348, 'paypal');
insert into payment (id_Payment, payment_Method) values (75115, 'check');
insert into payment (id_Payment, payment_Method) values (13813, 'credit card');
insert into payment (id_Payment, payment_Method) values (54552, 'credit card');
insert into payment (id_Payment, payment_Method) values (40887, 'cash');
insert into payment (id_Payment, payment_Method) values (45193, 'check');
insert into payment (id_Payment, payment_Method) values (68365, 'paypal');
insert into payment (id_Payment, payment_Method) values (41719, 'debit card');
insert into payment (id_Payment, payment_Method) values (15682, 'check');
insert into payment (id_Payment, payment_Method) values (44932, 'check');
insert into payment (id_Payment, payment_Method) values (66109, 'cash');
insert into payment (id_Payment, payment_Method) values (69041, 'check');
insert into payment (id_Payment, payment_Method) values (47750, 'credit card');
insert into payment (id_Payment, payment_Method) values (76882, 'credit card');
insert into payment (id_Payment, payment_Method) values (62240, 'check');
insert into payment (id_Payment, payment_Method) values (86063, 'paypal');
insert into payment (id_Payment, payment_Method) values (40506, 'cash');
insert into payment (id_Payment, payment_Method) values (31787, 'paypal');
insert into payment (id_Payment, payment_Method) values (61934, 'cash');
insert into payment (id_Payment, payment_Method) values (94202, 'paypal');
insert into payment (id_Payment, payment_Method) values (53604, 'debit card');
insert into payment (id_Payment, payment_Method) values (25041, 'credit card');
insert into payment (id_Payment, payment_Method) values (59206, 'debit card');
insert into payment (id_Payment, payment_Method) values (54675, 'cash');
insert into payment (id_Payment, payment_Method) values (49131, 'check');
insert into payment (id_Payment, payment_Method) values (35124, 'paypal');
insert into payment (id_Payment, payment_Method) values (61031, 'cash');
insert into payment (id_Payment, payment_Method) values (28225, 'paypal');
insert into payment (id_Payment, payment_Method) values (15682, 'check');
insert into payment (id_Payment, payment_Method) values (75281, 'credit card');
insert into payment (id_Payment, payment_Method) values (88613, 'debit card');
insert into payment (id_Payment, payment_Method) values (10669, 'credit card');
insert into payment (id_Payment, payment_Method) values (80905, 'debit card');
insert into payment (id_Payment, payment_Method) values (32862, 'credit card');
insert into payment (id_Payment, payment_Method) values (24359, 'debit card');
insert into payment (id_Payment, payment_Method) values (69964, 'paypal');
insert into payment (id_Payment, payment_Method) values (81659, 'paypal');
insert into payment (id_Payment, payment_Method) values (24054, 'debit card');
insert into payment (id_Payment, payment_Method) values (46487, 'credit card');
insert into payment (id_Payment, payment_Method) values (72780, 'debit card');
insert into payment (id_Payment, payment_Method) values (74924, 'check');
insert into payment (id_Payment, payment_Method) values (14268, 'credit card');
insert into payment (id_Payment, payment_Method) values (52881, 'credit card');
insert into payment (id_Payment, payment_Method) values (33044, 'paypal');
insert into payment (id_Payment, payment_Method) values (38116, 'check');
insert into payment (id_Payment, payment_Method) values (21721, 'paypal');
insert into payment (id_Payment, payment_Method) values (27342, 'debit card');
insert into payment (id_Payment, payment_Method) values (53668, 'credit card');
insert into payment (id_Payment, payment_Method) values (14861, 'paypal');
insert into payment (id_Payment, payment_Method) values (59844, 'credit card');
insert into payment (id_Payment, payment_Method) values (59691, 'paypal');
insert into payment (id_Payment, payment_Method) values (19004, 'cash');
insert into payment (id_Payment, payment_Method) values (32561, 'paypal');
insert into payment (id_Payment, payment_Method) values (50801, 'cash');
insert into payment (id_Payment, payment_Method) values (11799, 'paypal');
insert into payment (id_Payment, payment_Method) values (85689, 'paypal');
insert into payment (id_Payment, payment_Method) values (87250, 'credit card');
insert into payment (id_Payment, payment_Method) values (73730, 'check');
insert into payment (id_Payment, payment_Method) values (91039, 'cash');
insert into payment (id_Payment, payment_Method) values (72906, 'credit card');
insert into payment (id_Payment, payment_Method) values (19631, 'credit card');
insert into payment (id_Payment, payment_Method) values (64706, 'credit card');
insert into payment (id_Payment, payment_Method) values (74888, 'paypal');
insert into payment (id_Payment, payment_Method) values (34376, 'debit card');
insert into payment (id_Payment, payment_Method) values (81079, 'credit card');
insert into payment (id_Payment, payment_Method) values (26340, 'debit card');
insert into payment (id_Payment, payment_Method) values (39761, 'credit card');
insert into payment (id_Payment, payment_Method) values (32584, 'debit card');
insert into payment (id_Payment, payment_Method) values (93234, 'credit card');
insert into payment (id_Payment, payment_Method) values (20927, 'check');
insert into payment (id_Payment, payment_Method) values (68701, 'check');
insert into payment (id_Payment, payment_Method) values (66163, 'check');
insert into payment (id_Payment, payment_Method) values (72150, 'paypal');
insert into payment (id_Payment, payment_Method) values (45527, 'debit card');
insert into payment (id_Payment, payment_Method) values (46700, 'debit card');
insert into payment (id_Payment, payment_Method) values (28833, 'credit card');
insert into payment (id_Payment, payment_Method) values (77184, 'credit card');
insert into payment (id_Payment, payment_Method) values (13764, 'debit card');
insert into payment (id_Payment, payment_Method) values (95358, 'credit card');
insert into payment (id_Payment, payment_Method) values (54799, 'check');
insert into payment (id_Payment, payment_Method) values (23092, 'cash');
insert into payment (id_Payment, payment_Method) values (61243, 'cash');
insert into payment (id_Payment, payment_Method) values (30303, 'credit card');
insert into payment (id_Payment, payment_Method) values (50302, 'paypal');
insert into payment (id_Payment, payment_Method) values (72559, 'debit card');
insert into payment (id_Payment, payment_Method) values (77154, 'check');
insert into payment (id_Payment, payment_Method) values (98781, 'credit card');
insert into payment (id_Payment, payment_Method) values (74102, 'check');
insert into payment (id_Payment, payment_Method) values (26468, 'debit card');
insert into payment (id_Payment, payment_Method) values (80404, 'cash');
insert into payment (id_Payment, payment_Method) values (27729, 'check');
insert into payment (id_Payment, payment_Method) values (16097, 'paypal');
insert into payment (id_Payment, payment_Method) values (36384, 'paypal');
insert into payment (id_Payment, payment_Method) values (54066, 'cash');
insert into payment (id_Payment, payment_Method) values (74967, 'cash');
insert into payment (id_Payment, payment_Method) values (46951, 'paypal');
insert into payment (id_Payment, payment_Method) values (74209, 'credit card');
insert into payment (id_Payment, payment_Method) values (25324, 'debit card');
insert into payment (id_Payment, payment_Method) values (24800, 'check');
insert into payment (id_Payment, payment_Method) values (84316, 'paypal');
insert into payment (id_Payment, payment_Method) values (99283, 'check');
insert into payment (id_Payment, payment_Method) values (82724, 'paypal');
insert into payment (id_Payment, payment_Method) values (23787, 'credit card');
insert into payment (id_Payment, payment_Method) values (36655, 'cash');
insert into payment (id_Payment, payment_Method) values (58897, 'cash');
insert into payment (id_Payment, payment_Method) values (30341, 'credit card');
insert into payment (id_Payment, payment_Method) values (65379, 'check');
insert into payment (id_Payment, payment_Method) values (85165, 'cash');
insert into payment (id_Payment, payment_Method) values (67407, 'paypal');
insert into payment (id_Payment, payment_Method) values (86602, 'debit card');
insert into payment (id_Payment, payment_Method) values (22804, 'credit card');
insert into payment (id_Payment, payment_Method) values (66802, 'debit card');
insert into payment (id_Payment, payment_Method) values (50852, 'paypal');
insert into payment (id_Payment, payment_Method) values (84757, 'cash');
insert into payment (id_Payment, payment_Method) values (78421, 'debit card');
insert into payment (id_Payment, payment_Method) values (49934, 'credit card');
insert into payment (id_Payment, payment_Method) values (79399, 'cash');
insert into payment (id_Payment, payment_Method) values (20586, 'debit card');
insert into payment (id_Payment, payment_Method) values (17825, 'paypal');
insert into payment (id_Payment, payment_Method) values (32146, 'debit card');
insert into payment (id_Payment, payment_Method) values (43159, 'cash');
insert into payment (id_Payment, payment_Method) values (71590, 'debit card');
insert into payment (id_Payment, payment_Method) values (94185, 'credit card');
insert into payment (id_Payment, payment_Method) values (66127, 'debit card');
insert into payment (id_Payment, payment_Method) values (75561, 'cash');
insert into payment (id_Payment, payment_Method) values (75337, 'paypal');
insert into payment (id_Payment, payment_Method) values (57807, 'cash');
insert into payment (id_Payment, payment_Method) values (16986, 'check');
insert into payment (id_Payment, payment_Method) values (83930, 'credit card');
insert into payment (id_Payment, payment_Method) values (53574, 'cash');
insert into payment (id_Payment, payment_Method) values (62798, 'check');
insert into payment (id_Payment, payment_Method) values (81823, 'credit card');
insert into payment (id_Payment, payment_Method) values (76903, 'check');
insert into payment (id_Payment, payment_Method) values (85960, 'credit card');
insert into payment (id_Payment, payment_Method) values (91090, 'debit card');
insert into payment (id_Payment, payment_Method) values (86488, 'cash');
insert into payment (id_Payment, payment_Method) values (22422, 'debit card');
insert into payment (id_Payment, payment_Method) values (56371, 'credit card');
insert into payment (id_Payment, payment_Method) values (33815, 'debit card');
insert into payment (id_Payment, payment_Method) values (73911, 'check');
insert into payment (id_Payment, payment_Method) values (73613, 'credit card');
insert into payment (id_Payment, payment_Method) values (70774, 'paypal');
insert into payment (id_Payment, payment_Method) values (82060, 'paypal');
insert into payment (id_Payment, payment_Method) values (37524, 'debit card');
insert into payment (id_Payment, payment_Method) values (88198, 'check');
insert into payment (id_Payment, payment_Method) values (53302, 'cash');
insert into payment (id_Payment, payment_Method) values (29650, 'check');
insert into payment (id_Payment, payment_Method) values (79499, 'check');
insert into payment (id_Payment, payment_Method) values (49725, 'paypal');
insert into payment (id_Payment, payment_Method) values (14218, 'paypal');
insert into payment (id_Payment, payment_Method) values (30734, 'check');
insert into payment (id_Payment, payment_Method) values (73642, 'cash');
insert into payment (id_Payment, payment_Method) values (17428, 'credit card');
insert into payment (id_Payment, payment_Method) values (79308, 'debit card');
insert into payment (id_Payment, payment_Method) values (91245, 'check');
insert into payment (id_Payment, payment_Method) values (20620, 'debit card');
insert into payment (id_Payment, payment_Method) values (44968, 'cash');
insert into payment (id_Payment, payment_Method) values (69766, 'paypal');
insert into payment (id_Payment, payment_Method) values (58578, 'paypal');
insert into payment (id_Payment, payment_Method) values (42968, 'debit card');
insert into payment (id_Payment, payment_Method) values (25927, 'paypal');
insert into payment (id_Payment, payment_Method) values (50061, 'check');
insert into payment (id_Payment, payment_Method) values (73853, 'cash');
insert into payment (id_Payment, payment_Method) values (26389, 'paypal');
insert into payment (id_Payment, payment_Method) values (39361, 'paypal');
insert into payment (id_Payment, payment_Method) values (79982, 'credit card');
insert into payment (id_Payment, payment_Method) values (71308, 'debit card');
insert into payment (id_Payment, payment_Method) values (23133, 'cash');
insert into payment (id_Payment, payment_Method) values (56806, 'debit card');
insert into payment (id_Payment, payment_Method) values (73994, 'cash');
insert into payment (id_Payment, payment_Method) values (49101, 'cash');
insert into payment (id_Payment, payment_Method) values (94620, 'debit card');
insert into payment (id_Payment, payment_Method) values (76284, 'cash');
insert into payment (id_Payment, payment_Method) values (54894, 'cash');
insert into payment (id_Payment, payment_Method) values (85085, 'check');
insert into payment (id_Payment, payment_Method) values (13850, 'credit card');
insert into payment (id_Payment, payment_Method) values (65249, 'credit card');
insert into payment (id_Payment, payment_Method) values (95276, 'check');
insert into payment (id_Payment, payment_Method) values (87141, 'paypal');
insert into payment (id_Payment, payment_Method) values (23799, 'cash');
insert into payment (id_Payment, payment_Method) values (32172, 'check');
insert into payment (id_Payment, payment_Method) values (16099, 'debit card');
insert into payment (id_Payment, payment_Method) values (31183, 'check');
insert into payment (id_Payment, payment_Method) values (84597, 'check');
insert into payment (id_Payment, payment_Method) values (44321, 'cash');
insert into payment (id_Payment, payment_Method) values (16843, 'debit card');
insert into payment (id_Payment, payment_Method) values (19109, 'cash');
insert into payment (id_Payment, payment_Method) values (93930, 'cash');
insert into payment (id_Payment, payment_Method) values (27244, 'debit card');
insert into payment (id_Payment, payment_Method) values (16282, 'credit card');
insert into payment (id_Payment, payment_Method) values (67743, 'check');
insert into payment (id_Payment, payment_Method) values (56976, 'cash');
insert into payment (id_Payment, payment_Method) values (86810, 'cash');
insert into payment (id_Payment, payment_Method) values (50045, 'credit card');
insert into payment (id_Payment, payment_Method) values (71969, 'debit card');
insert into payment (id_Payment, payment_Method) values (94381, 'cash');
insert into payment (id_Payment, payment_Method) values (38979, 'paypal');
insert into payment (id_Payment, payment_Method) values (15318, 'cash');
insert into payment (id_Payment, payment_Method) values (81876, 'cash');
insert into payment (id_Payment, payment_Method) values (12909, 'paypal');
insert into payment (id_Payment, payment_Method) values (85449, 'credit card');
insert into payment (id_Payment, payment_Method) values (26294, 'cash');
insert into payment (id_Payment, payment_Method) values (42371, 'paypal');
insert into payment (id_Payment, payment_Method) values (46007, 'credit card');
insert into payment (id_Payment, payment_Method) values (70277, 'cash');
insert into payment (id_Payment, payment_Method) values (10487, 'debit card');
insert into payment (id_Payment, payment_Method) values (57542, 'check');
insert into payment (id_Payment, payment_Method) values (62997, 'cash');
insert into payment (id_Payment, payment_Method) values (59960, 'paypal');
insert into payment (id_Payment, payment_Method) values (34695, 'debit card');
insert into payment (id_Payment, payment_Method) values (99700, 'credit card');
insert into payment (id_Payment, payment_Method) values (46398, 'cash');
insert into payment (id_Payment, payment_Method) values (99881, 'cash');
insert into payment (id_Payment, payment_Method) values (58309, 'cash');
insert into payment (id_Payment, payment_Method) values (39206, 'debit card');
insert into payment (id_Payment, payment_Method) values (82953, 'credit card');
insert into payment (id_Payment, payment_Method) values (80226, 'credit card');
insert into payment (id_Payment, payment_Method) values (86959, 'debit card');
insert into payment (id_Payment, payment_Method) values (98059, 'cash');
insert into payment (id_Payment, payment_Method) values (81341, 'credit card');
insert into payment (id_Payment, payment_Method) values (38532, 'check');
insert into payment (id_Payment, payment_Method) values (17800, 'paypal');
insert into payment (id_Payment, payment_Method) values (65276, 'credit card');
insert into payment (id_Payment, payment_Method) values (51768, 'debit card');
insert into payment (id_Payment, payment_Method) values (89714, 'cash');
insert into payment (id_Payment, payment_Method) values (84055, 'cash');
insert into payment (id_Payment, payment_Method) values (82114, 'credit card');
insert into payment (id_Payment, payment_Method) values (71215, 'credit card');
insert into payment (id_Payment, payment_Method) values (28655, 'check');
insert into payment (id_Payment, payment_Method) values (10727, 'cash');
insert into payment (id_Payment, payment_Method) values (89554, 'credit card');
insert into payment (id_Payment, payment_Method) values (65306, 'check');
insert into payment (id_Payment, payment_Method) values (53732, 'credit card');
insert into payment (id_Payment, payment_Method) values (61368, 'cash');
insert into payment (id_Payment, payment_Method) values (45792, 'cash');
insert into payment (id_Payment, payment_Method) values (51583, 'paypal');
insert into payment (id_Payment, payment_Method) values (76227, 'debit card');
insert into payment (id_Payment, payment_Method) values (74147, 'cash');
insert into payment (id_Payment, payment_Method) values (64618, 'credit card');
insert into payment (id_Payment, payment_Method) values (77940, 'check');
insert into payment (id_Payment, payment_Method) values (62336, 'debit card');
insert into payment (id_Payment, payment_Method) values (20876, 'cash');
insert into payment (id_Payment, payment_Method) values (87721, 'debit card');
insert into payment (id_Payment, payment_Method) values (97005, 'cash');
insert into payment (id_Payment, payment_Method) values (73733, 'check');
insert into payment (id_Payment, payment_Method) values (63506, 'credit card');
insert into payment (id_Payment, payment_Method) values (67294, 'debit card');
insert into payment (id_Payment, payment_Method) values (49247, 'cash');
insert into payment (id_Payment, payment_Method) values (49015, 'check');
insert into payment (id_Payment, payment_Method) values (38020, 'paypal');
insert into payment (id_Payment, payment_Method) values (54363, 'paypal');
insert into payment (id_Payment, payment_Method) values (86960, 'credit card');
insert into payment (id_Payment, payment_Method) values (59156, 'debit card');
insert into payment (id_Payment, payment_Method) values (67957, 'credit card');
insert into payment (id_Payment, payment_Method) values (77498, 'check');
insert into payment (id_Payment, payment_Method) values (81689, 'paypal');
insert into payment (id_Payment, payment_Method) values (26164, 'paypal');
insert into payment (id_Payment, payment_Method) values (69545, 'check');
insert into payment (id_Payment, payment_Method) values (91187, 'check');
insert into payment (id_Payment, payment_Method) values (79051, 'cash');
insert into payment (id_Payment, payment_Method) values (70556, 'debit card');
insert into payment (id_Payment, payment_Method) values (76272, 'paypal');
insert into payment (id_Payment, payment_Method) values (95883, 'check');
insert into payment (id_Payment, payment_Method) values (10438, 'paypal');
insert into payment (id_Payment, payment_Method) values (12920, 'credit card');
insert into payment (id_Payment, payment_Method) values (83642, 'credit card');
insert into payment (id_Payment, payment_Method) values (49251, 'paypal');
insert into payment (id_Payment, payment_Method) values (85686, 'cash');
insert into payment (id_Payment, payment_Method) values (66450, 'check');
insert into payment (id_Payment, payment_Method) values (49642, 'check');
insert into payment (id_Payment, payment_Method) values (47757, 'credit card');
insert into payment (id_Payment, payment_Method) values (47011, 'check');
insert into payment (id_Payment, payment_Method) values (64777, 'credit card');
insert into payment (id_Payment, payment_Method) values (23430, 'paypal');
insert into payment (id_Payment, payment_Method) values (27432, 'paypal');
insert into payment (id_Payment, payment_Method) values (31042, 'paypal');
insert into payment (id_Payment, payment_Method) values (88283, 'credit card');
insert into payment (id_Payment, payment_Method) values (99095, 'cash');
insert into payment (id_Payment, payment_Method) values (39112, 'paypal');
insert into payment (id_Payment, payment_Method) values (69680, 'check');
insert into payment (id_Payment, payment_Method) values (51763, 'debit card');
insert into payment (id_Payment, payment_Method) values (27158, 'credit card');
insert into payment (id_Payment, payment_Method) values (78297, 'paypal');
insert into payment (id_Payment, payment_Method) values (75211, 'check');
insert into payment (id_Payment, payment_Method) values (98176, 'cash');
insert into payment (id_Payment, payment_Method) values (86260, 'debit card');
